// This file is @generated by prost-build.
/// Configuration for LiteParse document parsing.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LiteParseConfig {
    /// OCR language code (Tesseract format: "eng", "fra", "deu", etc.).
    #[prost(string, tag = "1")]
    pub ocr_language: ::prost::alloc::string::String,
    /// Whether OCR is enabled. When true, runs on text-sparse pages and embedded images.
    #[prost(bool, tag = "2")]
    pub ocr_enabled: bool,
    /// HTTP OCR server URL (uses Tesseract if not provided)
    #[prost(string, optional, tag = "3")]
    pub ocr_server_url: ::core::option::Option<::prost::alloc::string::String>,
    /// Extra HTTP headers sent with every request to `ocr_server_url`.
    /// Ignored when `ocr_server_url` is unset.
    #[prost(message, repeated, tag = "4")]
    pub ocr_server_headers: ::prost::alloc::vec::Vec<HttpHeader>,
    /// Path to tessdata directory. Falls back to TESSDATA_PREFIX env var if not set.
    #[prost(string, optional, tag = "5")]
    pub tessdata_path: ::core::option::Option<::prost::alloc::string::String>,
    /// Maximum number of pages to parse.
    #[prost(uint64, tag = "6")]
    pub max_pages: u64,
    /// Specific pages to parse (e.g., "1-5,10,15-20"). Unset means all pages.
    #[prost(string, optional, tag = "7")]
    pub target_pages: ::core::option::Option<::prost::alloc::string::String>,
    /// DPI for rendering pages (used for OCR and screenshots).
    #[prost(float, tag = "8")]
    pub dpi: f32,
    /// Output format.
    #[prost(enumeration = "OutputFormat", tag = "9")]
    pub output_format: i32,
    /// Keep very small text that would normally be filtered out.
    #[prost(bool, tag = "10")]
    pub preserve_very_small_text: bool,
    /// Password for encrypted/protected documents.
    #[prost(string, optional, tag = "11")]
    pub password: ::core::option::Option<::prost::alloc::string::String>,
    /// Suppress progress output.
    #[prost(bool, tag = "12")]
    pub quiet: bool,
    /// Number of concurrent OCR workers. Defaults to (number of CPU cores - 1), minimum 1.
    #[prost(uint64, tag = "13")]
    pub num_workers: u64,
    /// Controls how raster images are surfaced in markdown output. Has no
    /// effect on JSON / text outputs.
    #[prost(enumeration = "ImageMode", tag = "14")]
    pub image_mode: i32,
    /// Extract hyperlink annotations and render them as `[text](url)` in
    /// markdown output. Default on. Disable for benchmark parity with
    /// plain-text ground truth (the GT corpora never use link syntax).
    #[prost(bool, tag = "15")]
    pub extract_links: bool,
    /// Whether a systemic OCR failure (every OCR task failed *and* at least one
    /// was a text-sparse page whose primary text source was OCR) aborts the
    /// whole parse. Default `true`: surface the root cause instead of silently
    /// emitting blank pages. Set `false` to keep already-recovered native text
    /// and return partial results when OCR is unavailable — useful for callers
    /// that prefer a degraded document over a hard failure (e.g. when the host
    /// has its own OCR fallback or treats OCR as best-effort enrichment).
    #[prost(bool, tag = "16")]
    pub ocr_failure_fatal: bool,
    /// OCR request-hedging schedule (milliseconds) for the HTTP OCR engine.
    /// Empty (default) = no hedging. With multiple delays (e.g.
    /// `\[0, 5000, 10000, 15000, 20000\]`), each OCR attempt fires a duplicate
    /// request at every delay and takes the first to succeed — trading extra
    /// OCR-server load for lower tail latency on a slow/stuck pod. No effect on
    /// the Tesseract engine.
    #[prost(uint64, repeated, tag = "17")]
    pub ocr_hedge_delays_ms: ::prost::alloc::vec::Vec<u64>,
    /// Emit per-word sub-boxes on each `TextItem` (`TextItem.words`). Default
    /// `false`: a text item already carries its own box, and word boxes roughly
    /// double the text-item payload (size + napi marshalling), so they are only
    /// worth computing for callers doing word-level bbox attribution. When
    /// `false`, `TextItem.words` is always empty and the per-word tracking is
    /// skipped entirely (zero allocation).
    #[prost(bool, tag = "18")]
    pub emit_word_boxes: bool,
}
/// A single HTTP header as a name/value pair.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HttpHeader {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
/// Request to parse a file.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParseRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub file: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub config: ::core::option::Option<LiteParseConfig>,
}
/// Request to screenshot the pages of a file.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScreenshotRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub file: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub config: ::core::option::Option<LiteParseConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TextItem {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub x: f32,
    #[prost(float, tag = "3")]
    pub y: f32,
    #[prost(float, tag = "4")]
    pub width: f32,
    #[prost(float, tag = "5")]
    pub height: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParsedPage {
    #[prost(uint32, tag = "1")]
    pub page_number: u32,
    #[prost(float, tag = "2")]
    pub page_width: f32,
    #[prost(float, tag = "3")]
    pub page_height: f32,
    #[prost(message, repeated, tag = "4")]
    pub text_items: ::prost::alloc::vec::Vec<TextItem>,
}
/// Response with a parsed file
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParseResponse {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub pages: ::prost::alloc::vec::Vec<ParsedPage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScreenshotPage {
    #[prost(bytes = "vec", tag = "1")]
    pub image_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "2")]
    pub page_number: u32,
    #[prost(uint32, tag = "3")]
    pub height: u32,
    #[prost(uint32, tag = "4")]
    pub width: u32,
    #[prost(string, tag = "5")]
    pub mime_type: ::prost::alloc::string::String,
}
/// Screenshot response for a PDF file
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScreenshotResponse {
    #[prost(message, repeated, tag = "1")]
    pub screenshots: ::prost::alloc::vec::Vec<ScreenshotPage>,
}
/// Request to estimate the complexity of a file.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IsComplexRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub file: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub config: ::core::option::Option<LiteParseConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PageComplexityStats {
    #[prost(uint32, tag = "1")]
    pub page_number: u32,
    #[prost(uint64, tag = "2")]
    pub text_length: u64,
    #[prost(float, tag = "3")]
    pub text_coverage: f32,
    #[prost(bool, tag = "4")]
    pub has_substantial_images: bool,
    #[prost(uint32, tag = "5")]
    pub image_block_count: u32,
    #[prost(float, tag = "6")]
    pub image_coverage: f32,
    #[prost(float, tag = "7")]
    pub largest_image_coverage: f32,
    #[prost(bool, tag = "8")]
    pub full_page_image: bool,
    #[prost(float, optional, tag = "9")]
    pub uncoverted_vector_area: ::core::option::Option<f32>,
    #[prost(bool, tag = "10")]
    pub is_garbled: bool,
    #[prost(float, tag = "11")]
    pub page_area: f32,
    #[prost(bool, tag = "12")]
    pub needs_ocr: bool,
    #[prost(string, repeated, tag = "13")]
    pub reasons: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Response detailing the complexity estimation for a file
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IsComplexResponse {
    #[prost(message, repeated, tag = "1")]
    pub complexity: ::prost::alloc::vec::Vec<PageComplexityStats>,
}
/// Image handling for the markdown emitter.
///
/// * OFF — strip image references entirely.
/// * PLACEHOLDER (default) — emit `![](image_pN_K.png)` references in
///   reading order at each image's y position, but do not extract or
///   return pixel bytes. Keeps response size small while letting the LLM see
///   where figures live in the document.
/// * EMBED — same references, plus bytes returned via `ParseResult.images`.
///   Opt-in because pixel bytes can dwarf the text payload on image-heavy
///   PDFs. (Bytes plumbing lands in stage 11b — current variant is parsed but
///   behaves like PLACEHOLDER until then.)
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ImageMode {
    Unspecified = 0,
    Off = 1,
    Placeholder = 2,
    Embed = 3,
}
impl ImageMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "IMAGE_MODE_UNSPECIFIED",
            Self::Off => "IMAGE_MODE_OFF",
            Self::Placeholder => "IMAGE_MODE_PLACEHOLDER",
            Self::Embed => "IMAGE_MODE_EMBED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "IMAGE_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            "IMAGE_MODE_OFF" => Some(Self::Off),
            "IMAGE_MODE_PLACEHOLDER" => Some(Self::Placeholder),
            "IMAGE_MODE_EMBED" => Some(Self::Embed),
            _ => None,
        }
    }
}
/// Supported output formats.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OutputFormat {
    Unspecified = 0,
    Json = 1,
    Text = 2,
    Markdown = 3,
}
impl OutputFormat {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OUTPUT_FORMAT_UNSPECIFIED",
            Self::Json => "OUTPUT_FORMAT_JSON",
            Self::Text => "OUTPUT_FORMAT_TEXT",
            Self::Markdown => "OUTPUT_FORMAT_MARKDOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OUTPUT_FORMAT_UNSPECIFIED" => Some(Self::Unspecified),
            "OUTPUT_FORMAT_JSON" => Some(Self::Json),
            "OUTPUT_FORMAT_TEXT" => Some(Self::Text),
            "OUTPUT_FORMAT_MARKDOWN" => Some(Self::Markdown),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod parser_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// The Parser service definition.
    #[derive(Debug, Clone)]
    pub struct ParserServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ParserServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ParserServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ParserServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ParserServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Parse a file
        pub async fn parse(
            &mut self,
            request: impl tonic::IntoRequest<super::ParseRequest>,
        ) -> std::result::Result<tonic::Response<super::ParseResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/parser.ParserService/Parse",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("parser.ParserService", "Parse"));
            self.inner.unary(req, path, codec).await
        }
        /// Screenshot the pages of a PDF file
        pub async fn screenshot(
            &mut self,
            request: impl tonic::IntoRequest<super::ScreenshotRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ScreenshotResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/parser.ParserService/Screenshot",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("parser.ParserService", "Screenshot"));
            self.inner.unary(req, path, codec).await
        }
        /// Estimate the complexity of a file and the need for OCR
        pub async fn is_complex(
            &mut self,
            request: impl tonic::IntoRequest<super::IsComplexRequest>,
        ) -> std::result::Result<
            tonic::Response<super::IsComplexResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/parser.ParserService/IsComplex",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("parser.ParserService", "IsComplex"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod parser_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ParserServiceServer.
    #[async_trait]
    pub trait ParserService: std::marker::Send + std::marker::Sync + 'static {
        /// Parse a file
        async fn parse(
            &self,
            request: tonic::Request<super::ParseRequest>,
        ) -> std::result::Result<tonic::Response<super::ParseResponse>, tonic::Status>;
        /// Screenshot the pages of a PDF file
        async fn screenshot(
            &self,
            request: tonic::Request<super::ScreenshotRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ScreenshotResponse>,
            tonic::Status,
        >;
        /// Estimate the complexity of a file and the need for OCR
        async fn is_complex(
            &self,
            request: tonic::Request<super::IsComplexRequest>,
        ) -> std::result::Result<
            tonic::Response<super::IsComplexResponse>,
            tonic::Status,
        >;
    }
    /// The Parser service definition.
    #[derive(Debug)]
    pub struct ParserServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ParserServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ParserServiceServer<T>
    where
        T: ParserService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/parser.ParserService/Parse" => {
                    #[allow(non_camel_case_types)]
                    struct ParseSvc<T: ParserService>(pub Arc<T>);
                    impl<
                        T: ParserService,
                    > tonic::server::UnaryService<super::ParseRequest> for ParseSvc<T> {
                        type Response = super::ParseResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ParseRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ParserService>::parse(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ParseSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/parser.ParserService/Screenshot" => {
                    #[allow(non_camel_case_types)]
                    struct ScreenshotSvc<T: ParserService>(pub Arc<T>);
                    impl<
                        T: ParserService,
                    > tonic::server::UnaryService<super::ScreenshotRequest>
                    for ScreenshotSvc<T> {
                        type Response = super::ScreenshotResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ScreenshotRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ParserService>::screenshot(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ScreenshotSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/parser.ParserService/IsComplex" => {
                    #[allow(non_camel_case_types)]
                    struct IsComplexSvc<T: ParserService>(pub Arc<T>);
                    impl<
                        T: ParserService,
                    > tonic::server::UnaryService<super::IsComplexRequest>
                    for IsComplexSvc<T> {
                        type Response = super::IsComplexResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::IsComplexRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ParserService>::is_complex(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = IsComplexSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ParserServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "parser.ParserService";
    impl<T> tonic::server::NamedService for ParserServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
